refactor to use timestamp cache

diff --git a/rundeck/tests/docker/jobs.yaml b/rundeck/tests/docker/jobs.yaml
--- a/rundeck/tests/docker/jobs.yaml
+++ b/rundeck/tests/docker/jobs.yaml
@@ -1,5 +1,33 @@
-- name: random-pass-or-fail
-  uuid: 13fb8e14-2263-4726-a4c0-b7268471062a
+- name: fast-job-pass
+  uuid: 1fastjob-pass-1111-1111-111111111111
+  description: ''
+  executionEnabled: true
+  loglevel: INFO
+  multipleExecutions: true
+  sequence:
+    keepgoing: false
+    strategy: node-first
+    commands:
+    - script: |-
+        #!/bin/bash
+        echo "Task completed successfully."
+        exit 0
+- name: fast-job-fail
+  uuid: 1fastjob-fail-1111-1111-111111111111
+  description: ''
+  executionEnabled: true
+  loglevel: INFO
+  multipleExecutions: true
+  sequence:
+    keepgoing: false
+    strategy: node-first
+    commands:
+    - script: |-
+        #!/bin/bash
+        echo "Task failed successfully."
+        exit 1
+- name: slow-random-pass-or-fail
+  uuid: 1slowjob-pass-fail-1111-111111111111
   description: ''
   executionEnabled: true
   loglevel: INFO
